const SHOP_DATA = [
  {
    id: 1,
    author: 'Richard Hamming',
    title: 'The Art of Doing Science and Engineering: Learning to Learn',
    description: 'The Art of Doing Science and Engineering is a reminder that a childlike capacity for learning and creativity are accessible to everyone.',
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/art-science-eng.jpg',
    price: 23,
  },
  {
    id: 2,
    author: 'Jordan Mechner',
    title: 'The Making of Prince of Persia: Journals 1985-1993',
    description: 'In The Making of Prince of Persia, on the 30th anniversary of the game’s release, Mechner looks back at the journals he kept from 1985 to 1993.',
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/prince-of-persia.jpg',
    price: 25,
  },
  {
    id: 3,
    author: 'Nadia Eghbal',
    title: 'Working in Public: The Making and Maintenance of Open Source',
    description: 'Nadia Eghbal takes an inside look at modern open source and offers a model through which to understand the challenges faced by online creators.',
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/working-in-public.jpg',
    price: 28,
  },
  {
    id: 4,
    author: 'Elad Gil',
    title: 'High Growth Handbook',
    description: 'High Growth Handbook is the playbook for turning a startup into a unicorn and navigating the most complex challenges that confront leaders and operators in high-growth startups.',
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/hgh.jpg',
    price: 28,
  },  
  {
    id: 5,
    author: 'M. Mitchell Waldrop',
    title: 'The Dream Machine',
    description: 'In a simultaneously compelling personal narrative and comprehensive historical exposition, Waldrop tells the story of the man who not only instigated the work that led to the internet, but also shifted our understanding of what computers were and could be.',
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/tdm.jpg',
    price: 20,
  },
  {
    id: 6,
    author: 'Tyler Cowen',
    title: 'Stubborn Attachments',
    description: 'Cowen’s latest book, at its heart, makes the contemporary moral case for economic growth and in doing so engenders a great dose of inspiration and optimism about our future possibilities.',
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/sa.jpg',
    price: 28,
  },
  {
    id: 7,
    author: 'Martin Gurri',
    title: 'The Revolt of the Public and the Crisis of Authority in the New Millennium',
    description: 'The Revolt of the Public tells the story of how insurgencies, enabled by digital devices and a vast information sphere, have mobilized millions of ordinary people around the world.',
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/rotp.jpg',
    price: 28,
  },
  {
    id: 8,
    author: 'Will Larson',
    title: 'An Elegant Puzzle: Systems of Engineering Management',
    description: "An Elegant Puzzle balances structured principles and human-centric thinking to help any leader create more effective and rewarding organizations for engineers to thrive in.",
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/aep.jpg',
    price: 28,
  },
  {
    id: 9,
    author: 'Bailey Richardson, Kevin Huynh, Kai Elmer Sotto',
    title: 'Get Together',
    description: "Every organization holds the potential to build and sustain a thriving community. Get Together shows readers how companies and customers, artist and fans, or organizers and advocates, can join forces to accomplish more together than they could have alone.",
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/gt.jpg',
    price: 28,
  },
  {
    id: 10,
    author: 'Donald W. Braben',
    title: 'Scientific Freedom: The Elixir of Civilization',
    description: 'Support for such research can be low risk and offer rich rewards, Braben argues, but it requires rethinking the processes used to discover and sponsor scientists with groundbreaking ideas—and then giving those innovators the freedom to explore.',
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/scientific-freedom.jpg',
    price: 28,
  },
  {
    id: 11,
    author: 'Michael S. Malone',
    title: 'The Big Score: The Billion-Dollar Story of Silicon Valley',
    description: 'Drawing on unvarnished interviews, Malone punctuates this history with incisive profiles of early luminaries, including William Shockley and Steve Jobs, when they were struggling entrepreneurs. With stories of ingenuity and individual sacrifice at its core, The Big Score is an indelible portrait of the high-agency spirit of early Silicon Valley.',
    imageUrl: 'https://press.stripe.com/img/v3/books/covers/the-big-score.jpg',
    price: 24,
  },
];

export default SHOP_DATA;